# ---- This is <config.yaml> ----
#
# Your main data directory (data_dir) should contain individual folders for
# each test site.

# The 'SITE_DIR' for your job is built based on your 'data_dir' and 'site'
# inputs.
# 
# Within your 'SITE_DIR', there must be a 'GA_geotiff' folder with the original
# geotiff intensity images processed by GA.
#
# Individual folders for each image pair will be placed into 'SITE_DIR'
#
# All other parameters are set to 'standard' settings, but can be adjusted
# for further testing and development. 
#
# -------------------------------------------------------------------------- #
# -------------------------------------------------------------------------- #

# Set path to main data directory
data_dir: "/g/data/jk72/jl0818/DATA/fast_ice_tests"

# Define study site
site: "McMurdo"

# Set min and max values for allowed temporal baseline
min_temp_baseline: 11.9
max_temp_baseline: 12.1

# Set EPSG code for outputs (standard for Antarctica: 3031)
output_epsg: 3031

# Window sizes (published standard settings 11, 21, 33)
window_list:
  - 11
  - 21
  - 33

# Do you want to overwrite already existing products? (true/false)
# Overwrite option actually not fully implemented yet
overwrite: false

# Compute normprod locally (true/false)
# Approx. 35 minutes per image per
# Not recommended when processing multiple image pairs!
compute_normprod_locally: false

# Save intermediate products during normprod_smovar computation? (true/false)
# Only needed during development or trouble-shooting
save_intermediate_products: false

# Set min/max values for normprod_smovar RGB scaling
# This is what SAM will see
# Published default settings are [-0.5, +1.0]
NP_min: -0.5
NP_max: 1.0

# Set path to landmask shapefile
landmask_shapefile_path: "/g/data/jk72/jl0818/DATA/fast_ice_tests/coastline_shapefiles/add_coastline_high_res_polygon_v7_10/add_coastline_high_res_polygon_v7_10.shp"

# Set landmask erosion in number of pixels on full resolution image
# The workflow will produce a true and an eroded landmask
# Landmask erosion is needed to avoid boundary effects from SAM
# Final fast ice map should be done with the "true" landmask
erode_landmask: 100

# Set loglevel (DEBUG/INFO)
loglevel: INFO

# -------------------------------------------------------------------------- #
# -------------------------------------------------------------------------- #

# PARAMETERS SPECIFIC TO DISTRIBUTED BATCH PROCESSING

# Set path to your local conda.sh file
# Required to activate anaconda environment during distributed normprod processing
conda_sh: "/g/data/jk72/jl0818/miniconda3_jo/etc/profile.d/conda.sh"

# Set name of conda environment for normprod processing
conda_env: "NORMPROD"

# Set path to pbs_template file
# Recommended to keep in your local 'config' folder
pbs_template: "../config/pbs_template.txt"

# Set path to run_script for distributed batch processing
# Recommended to keep in your local 'utils' folder
pbs_run_script: "./utils/run_single_pair_as_separate_job.py"

# Set path to log_dir for distributed batch processing
# Place this wherever you want to keep track of your processing
# Individual PBS scripts will also be saved here
pbs_log_dir: "./batch_processing_logs/McMurdo/logs"

# -------------------------------------------------------------------------- #
# -------------------------------------------------------------------------- #

# ---- End of <config.yaml> ----

